/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    int val = 50;
//			input operand example
    __asm volatile("MOV R0,%0"::"r"(val));
// output operand example

    int control_reg;
    __asm volatile("MRS %0, CONTROL": "=r" (control_reg));


// Var1 to var2

    int var1 = 60, var2;

    __asm ("MOV %0,%1": "=r"(var2): "r" (var1));

//	pointer variable to a variable

    int normal, *pointer;

    pointer = (int*)0x20000008;

    __asm volatile("LDR %0, [%1]": "=r"(normal):"r"(pointer));


	for(;;);
}
